services:
  dev:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - .:/workspaces/db-sql-intro-lab
    command: sleep infinity
    networks: [labnet]
    depends_on: [postgres, adminer]

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks: [labnet]

  adminer:
    image: adminer:latest
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "8080:8080"
    networks: [labnet]

volumes:
  pgdata:

networks:
  labnet:
